drop extension if exists "pg_net";


  create table "public"."producto" (
    "id" bigint generated by default as identity not null,
    "nombre" text not null,
    "modelo" text,
    "medida" text,
    "tipo_id" integer,
    "existencia" smallint not null,
    "precio_proveedor" numeric not null,
    "precio_publico" numeric not null,
    "user_id" uuid not null
      );


alter table "public"."producto" enable row level security;


  create table "public"."tipo" (
    "id" bigint generated by default as identity not null,
    "tipo_de_producto" text not null,
    "user_id" uuid not null
      );


alter table "public"."tipo" enable row level security;

CREATE UNIQUE INDEX producto_pkey ON public.producto USING btree (id);

CREATE UNIQUE INDEX producto_user_nombre_unique ON public.producto USING btree (user_id, lower(TRIM(BOTH FROM nombre)));

CREATE UNIQUE INDEX tipo_pkey ON public.tipo USING btree (id);

CREATE UNIQUE INDEX tipo_user_tipo_de_producto_unique ON public.tipo USING btree (user_id, lower(TRIM(BOTH FROM tipo_de_producto)));

alter table "public"."producto" add constraint "producto_pkey" PRIMARY KEY using index "producto_pkey";

alter table "public"."tipo" add constraint "tipo_pkey" PRIMARY KEY using index "tipo_pkey";

alter table "public"."producto" add constraint "producto_tipo_id_fkey" FOREIGN KEY (tipo_id) REFERENCES public.tipo(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."producto" validate constraint "producto_tipo_id_fkey";

alter table "public"."producto" add constraint "producto_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."producto" validate constraint "producto_user_id_fkey";

alter table "public"."tipo" add constraint "tipo_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."tipo" validate constraint "tipo_user_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.rls_auto_enable()
 RETURNS event_trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'pg_catalog'
AS $function$
DECLARE
  cmd record;
BEGIN
  FOR cmd IN
    SELECT *
    FROM pg_event_trigger_ddl_commands()
    WHERE command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      AND object_type IN ('table','partitioned table')
  LOOP
     IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog','information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
      BEGIN
        EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);
        RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
      EXCEPTION
        WHEN OTHERS THEN
          RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
      END;
     ELSE
        RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
     END IF;
  END LOOP;
END;
$function$
;

grant delete on table "public"."producto" to "anon";

grant insert on table "public"."producto" to "anon";

grant references on table "public"."producto" to "anon";

grant select on table "public"."producto" to "anon";

grant trigger on table "public"."producto" to "anon";

grant truncate on table "public"."producto" to "anon";

grant update on table "public"."producto" to "anon";

grant delete on table "public"."producto" to "authenticated";

grant insert on table "public"."producto" to "authenticated";

grant references on table "public"."producto" to "authenticated";

grant select on table "public"."producto" to "authenticated";

grant trigger on table "public"."producto" to "authenticated";

grant truncate on table "public"."producto" to "authenticated";

grant update on table "public"."producto" to "authenticated";

grant delete on table "public"."producto" to "service_role";

grant insert on table "public"."producto" to "service_role";

grant references on table "public"."producto" to "service_role";

grant select on table "public"."producto" to "service_role";

grant trigger on table "public"."producto" to "service_role";

grant truncate on table "public"."producto" to "service_role";

grant update on table "public"."producto" to "service_role";

grant delete on table "public"."tipo" to "anon";

grant insert on table "public"."tipo" to "anon";

grant references on table "public"."tipo" to "anon";

grant select on table "public"."tipo" to "anon";

grant trigger on table "public"."tipo" to "anon";

grant truncate on table "public"."tipo" to "anon";

grant update on table "public"."tipo" to "anon";

grant delete on table "public"."tipo" to "authenticated";

grant insert on table "public"."tipo" to "authenticated";

grant references on table "public"."tipo" to "authenticated";

grant select on table "public"."tipo" to "authenticated";

grant trigger on table "public"."tipo" to "authenticated";

grant truncate on table "public"."tipo" to "authenticated";

grant update on table "public"."tipo" to "authenticated";

grant delete on table "public"."tipo" to "service_role";

grant insert on table "public"."tipo" to "service_role";

grant references on table "public"."tipo" to "service_role";

grant select on table "public"."tipo" to "service_role";

grant trigger on table "public"."tipo" to "service_role";

grant truncate on table "public"."tipo" to "service_role";

grant update on table "public"."tipo" to "service_role";


  create policy "usuario crea sus productos"
  on "public"."producto"
  as permissive
  for insert
  to public
with check ((auth.uid() = user_id));



  create policy "usuario edita sus productos"
  on "public"."producto"
  as permissive
  for update
  to public
using ((auth.uid() = user_id));



  create policy "usuario elimina sus productos"
  on "public"."producto"
  as permissive
  for delete
  to public
using ((auth.uid() = user_id));



  create policy "usuario ve sus productos"
  on "public"."producto"
  as permissive
  for select
  to public
using ((auth.uid() = user_id));



  create policy "usuario crea sus tipos"
  on "public"."tipo"
  as permissive
  for insert
  to public
with check ((auth.uid() = user_id));



  create policy "usuario edita sus tipos"
  on "public"."tipo"
  as permissive
  for update
  to public
using ((auth.uid() = user_id));



  create policy "usuario elimina sus tipos"
  on "public"."tipo"
  as permissive
  for delete
  to public
using ((auth.uid() = user_id));



  create policy "usuario ve sus tipos"
  on "public"."tipo"
  as permissive
  for select
  to public
using ((auth.uid() = user_id));



